service:
  name: nest-serverless-framework-demo
   
plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-warmup
  
custom:
  # Enable warmup on all functions (only for production and staging)
  warmup:
    enabled: true  

provider:
  name: aws
  runtime: nodejs12.x
   
functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: ./dist/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}